const soups = [
  {
    id: 716437,
    title: "Chilled Cucumber Avocado Soup with Yogurt and Kefir",
    image: "https://spoonacular.com/recipeImages/716437-312x231.jpg",
    imageType: "jpg",
  },
  {
    id: 663559,
    title: "Tomato and lentil soup",
    image: "https://spoonacular.com/recipeImages/663559-312x231.jpg",
    imageType: "jpg",
  },
  {
    id: 660405,
    title: "Smoky Black Bean Soup With Sweet Potato & Kale",
    image: "https://spoonacular.com/recipeImages/660405-312x231.jpg",
    imageType: "jpg",
  },
  {
    id: 636602,
    title: "Butternut Squash Soup (In Half An Hour!)",
    image: "https://spoonacular.com/recipeImages/636602-312x231.jpg",
    imageType: "jpg",
  },
  {
    id: 652393,
    title: "Moosewood Lentil Soup",
    image: "https://spoonacular.com/recipeImages/652393-312x231.jpg",
    imageType: "jpg",
  },
  {
    id: 633097,
    title: "Autumn In A Bowl Soup",
    image: "https://spoonacular.com/recipeImages/633097-312x231.jpg",
    imageType: "jpg",
  },
  {
    id: 652038,
    title: "Minted Pea & Spinach Soup",
    image: "https://spoonacular.com/recipeImages/652038-312x231.jpg",
    imageType: "jpg",
  },
  {
    id: 1096213,
    title: "Creamy, Healthy Asparagus Soup with Avocado and Fennel",
    image: "https://spoonacular.com/recipeImages/1096213-312x231.jpg",
    imageType: "jpg",
  },
  {
    id: 631834,
    title: "10-Minute Bean Stew",
    image: "https://spoonacular.com/recipeImages/631834-312x231.jpg",
    imageType: "jpg",
  },
  {
    id: 637164,
    title: "Carrot and Coriander Soup",
    image: "https://spoonacular.com/recipeImages/637164-312x231.jpg",
    imageType: "jpg",
  },
];

const tomato = {
  vegetarian: true,
  vegan: true,
  glutenFree: true,
  dairyFree: true,
  veryHealthy: true,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 8,
  gaps: "no",
  preparationMinutes: -1,
  cookingMinutes: -1,
  aggregateLikes: 11,
  healthScore: 100,
  creditsText: "foodista.com",
  sourceName: "foodista.com",
  pricePerServing: 126.27,
  extendedIngredients: [
    {
      id: 4053,
      aisle: "Oil, Vinegar, Salad Dressing",
      image: "olive-oil.jpg",
      consistency: "LIQUID",
      name: "olive oil",
      nameClean: "olive oil",
      original: "2 Tbs olive oil",
      originalName: "olive oil",
      amount: 2.0,
      unit: "Tbs",
      meta: [],
      measures: {
        us: { amount: 2.0, unitShort: "Tbs", unitLong: "Tbs" },
        metric: { amount: 2.0, unitShort: "Tbs", unitLong: "Tbs" },
      },
    },
    {
      id: 11282,
      aisle: "Produce",
      image: "brown-onion.png",
      consistency: "SOLID",
      name: "onion",
      nameClean: "onion",
      original: "1 onion, chopped",
      originalName: "onion, chopped",
      amount: 1.0,
      unit: "",
      meta: ["chopped"],
      measures: {
        us: { amount: 1.0, unitShort: "", unitLong: "" },
        metric: { amount: 1.0, unitShort: "", unitLong: "" },
      },
    },
    {
      id: 11215,
      aisle: "Produce",
      image: "garlic.png",
      consistency: "SOLID",
      name: "garlic",
      nameClean: "garlic",
      original: "2 cloves garlic, minced",
      originalName: "garlic, minced",
      amount: 2.0,
      unit: "cloves",
      meta: ["minced"],
      measures: {
        us: { amount: 2.0, unitShort: "cloves", unitLong: "cloves" },
        metric: { amount: 2.0, unitShort: "cloves", unitLong: "cloves" },
      },
    },
    {
      id: 11124,
      aisle: "Produce",
      image: "sliced-carrot.png",
      consistency: "SOLID",
      name: "carrots",
      nameClean: "carrot",
      original: "3 carrots cut into cubes",
      originalName: "carrots cut into cubes",
      amount: 3.0,
      unit: "",
      meta: ["cut into cubes"],
      measures: {
        us: { amount: 3.0, unitShort: "", unitLong: "" },
        metric: { amount: 3.0, unitShort: "", unitLong: "" },
      },
    },
    {
      id: 10011693,
      aisle: "Canned and Jarred",
      image: "tomatoes-canned.png",
      consistency: "SOLID",
      name: "canned tomatoes",
      nameClean: "canned tomatoes",
      original: "480g canned chopped tomatoes",
      originalName: "canned chopped tomatoes",
      amount: 480.0,
      unit: "g",
      meta: ["canned", "chopped"],
      measures: {
        us: { amount: 1.058, unitShort: "lb", unitLong: "pounds" },
        metric: { amount: 480.0, unitShort: "g", unitLong: "grams" },
      },
    },
    {
      id: 2004,
      aisle: "Produce;Spices and Seasonings",
      image: "bay-leaves.jpg",
      consistency: "SOLID",
      name: "bay leaf",
      nameClean: "bay leaves",
      original: "1 bay leaf",
      originalName: "bay leaf",
      amount: 1.0,
      unit: "",
      meta: [],
      measures: {
        us: { amount: 1.0, unitShort: "", unitLong: "" },
        metric: { amount: 1.0, unitShort: "", unitLong: "" },
      },
    },
    {
      id: 14412,
      aisle: "Beverages",
      image: "water.png",
      consistency: "LIQUID",
      name: "water",
      nameClean: "water",
      original: "1.3 l water",
      originalName: "water",
      amount: 1.3,
      unit: "l",
      meta: [],
      measures: {
        us: { amount: 1.374, unitShort: "qt", unitLong: "quarts" },
        metric: { amount: 1.3, unitShort: "l", unitLong: "liters" },
      },
    },
    {
      id: 16069,
      aisle: "Pasta and Rice;Canned and Jarred;Produce",
      image: "lentils-green.jpg",
      consistency: "SOLID",
      name: "lentils",
      nameClean: "legumes",
      original: "250 g lentils",
      originalName: "lentils",
      amount: 250.0,
      unit: "g",
      meta: [],
      measures: {
        us: { amount: 8.818, unitShort: "oz", unitLong: "ounces" },
        metric: { amount: 250.0, unitShort: "g", unitLong: "grams" },
      },
    },
    {
      id: 2047,
      aisle: "Spices and Seasonings",
      image: "salt.jpg",
      consistency: "SOLID",
      name: "salt",
      nameClean: "table salt",
      original: "¼ tsp salt",
      originalName: "salt",
      amount: 0.25,
      unit: "tsp",
      meta: [],
      measures: {
        us: { amount: 0.25, unitShort: "tsps", unitLong: "teaspoons" },
        metric: { amount: 0.25, unitShort: "tsps", unitLong: "teaspoons" },
      },
    },
    {
      id: 11297,
      aisle: "Produce;Spices and Seasonings",
      image: "parsley.jpg",
      consistency: "SOLID",
      name: "parsley",
      nameClean: "parsley",
      original: "1 bunch chopped parsley",
      originalName: "chopped parsley",
      amount: 1.0,
      unit: "bunch",
      meta: ["chopped"],
      measures: {
        us: { amount: 1.0, unitShort: "bunch", unitLong: "bunch" },
        metric: { amount: 1.0, unitShort: "bunch", unitLong: "bunch" },
      },
    },
  ],
  id: 663559,
  title: "Tomato and lentil soup",
  readyInMinutes: 45,
  servings: 4,
  sourceUrl: "https://www.foodista.com/recipe/5V4PTMT2/tomato-and-lentil-soup",
  image: "https://spoonacular.com/recipeImages/663559-556x370.jpg",
  imageType: "jpg",
  summary:
    'Tomato and lentil soup takes about <b>about 45 minutes</b> from beginning to end. Watching your figure? This gluten free, dairy free, lacto ovo vegetarian, and vegan recipe has <b>358 calories</b>, <b>19g of protein</b>, and <b>8g of fat</b> per serving. This recipe serves 4 and costs $1.26 per serving. 11 person were impressed by this recipe. It works well as an affordable main course for <b>Autumn</b>. A mixture of carrots, bay leaf, parsley, and a handful of other ingredients are all it takes to make this recipe so yummy. It is brought to you by Foodista. Taking all factors into account, this recipe <b>earns a spoonacular score of 97%</b>, which is super. If you like this recipe, you might also like recipes such as <a href="https://spoonacular.com/recipes/lentil-tomato-soup-108370">Lentil & Tomato Soup</a>, <a href="https://spoonacular.com/recipes/lentil-tomato-soup-398380">Lentil-Tomato Soup</a>, and <a href="https://spoonacular.com/recipes/tomato-and-lentil-soup-482854">Tomato and Lentil Soup</a>.',
  cuisines: [],
  dishTypes: ["soup", "lunch", "main course", "main dish", "dinner"],
  diets: [
    "gluten free",
    "dairy free",
    "lacto ovo vegetarian",
    "whole 30",
    "vegan",
  ],
  occasions: ["fall", "winter"],
  winePairing: { pairedWines: [], pairingText: "", productMatches: [] },
  instructions:
    "Saut onion and garlic in olive oil for 5 minutes.\nAdd the carrot, saut for another 2 minutes.\nAdd tomatoes, bay leaf and water, stir and bring to the boil.\nStir in lentils, season with salt and cook for 5 minutes.\nBefore serving sprinkle with chopped parsley.",
  analyzedInstructions: [
    {
      name: "",
      steps: [
        {
          number: 1,
          step: "Saut onion and garlic in olive oil for 5 minutes.",
          ingredients: [
            {
              id: 4053,
              name: "olive oil",
              localizedName: "olive oil",
              image: "olive-oil.jpg",
            },
            {
              id: 11215,
              name: "garlic",
              localizedName: "garlic",
              image: "garlic.png",
            },
            {
              id: 11282,
              name: "onion",
              localizedName: "onion",
              image: "brown-onion.png",
            },
          ],
          equipment: [],
          length: { number: 5, unit: "minutes" },
        },
        {
          number: 2,
          step: "Add the carrot, saut for another 2 minutes.",
          ingredients: [
            {
              id: 11124,
              name: "carrot",
              localizedName: "carrot",
              image: "sliced-carrot.png",
            },
          ],
          equipment: [],
          length: { number: 2, unit: "minutes" },
        },
        {
          number: 3,
          step: "Add tomatoes, bay leaf and water, stir and bring to the boil.",
          ingredients: [
            {
              id: 2004,
              name: "bay leaves",
              localizedName: "bay leaves",
              image: "bay-leaves.jpg",
            },
            {
              id: 11529,
              name: "tomato",
              localizedName: "tomato",
              image: "tomato.png",
            },
            {
              id: 14412,
              name: "water",
              localizedName: "water",
              image: "water.png",
            },
          ],
          equipment: [],
        },
        {
          number: 4,
          step: "Stir in lentils, season with salt and cook for 5 minutes.",
          ingredients: [
            {
              id: 10316069,
              name: "lentils",
              localizedName: "lentils",
              image: "lentils-brown.jpg",
            },
            {
              id: 2047,
              name: "salt",
              localizedName: "salt",
              image: "salt.jpg",
            },
          ],
          equipment: [],
          length: { number: 5, unit: "minutes" },
        },
        {
          number: 5,
          step: "Before serving sprinkle with chopped parsley.",
          ingredients: [
            {
              id: 11297,
              name: "parsley",
              localizedName: "parsley",
              image: "parsley.jpg",
            },
          ],
          equipment: [],
        },
      ],
    },
  ],
  originalId: null,
  spoonacularSourceUrl: "https://spoonacular.com/tomato-and-lentil-soup-663559",
};

const cucumber = {
  vegetarian: true,
  vegan: false,
  glutenFree: true,
  dairyFree: false,
  veryHealthy: true,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 3,
  gaps: "no",
  preparationMinutes: -1,
  cookingMinutes: -1,
  aggregateLikes: 171,
  healthScore: 54,
  creditsText: "Full Belly Sisters",
  license: "CC BY-SA 3.0",
  sourceName: "Full Belly Sisters",
  pricePerServing: 216.29,
  extendedIngredients: [
    {
      id: 9037,
      aisle: "Produce",
      image: "avocado.jpg",
      consistency: "SOLID",
      name: "avocado",
      nameClean: "avocado",
      original: "1/2 avocado",
      originalName: "avocado",
      amount: 0.5,
      unit: "",
      meta: [],
      measures: {
        us: { amount: 0.5, unitShort: "", unitLong: "" },
        metric: { amount: 0.5, unitShort: "", unitLong: "" },
      },
    },
    {
      id: 11206,
      aisle: "Produce",
      image: "cucumber.jpg",
      consistency: "SOLID",
      name: "cucumbers",
      nameClean: "cucumber",
      original: "5-6 persian cucumbers",
      originalName: "persian cucumbers",
      amount: 5.0,
      unit: "",
      meta: [],
      measures: {
        us: { amount: 5.0, unitShort: "", unitLong: "" },
        metric: { amount: 5.0, unitShort: "", unitLong: "" },
      },
    },
    {
      id: 9132,
      aisle: "Produce",
      image: "red-grapes.jpg",
      consistency: "SOLID",
      name: "grapes",
      nameClean: "grapes",
      original: "small handful of grapes",
      originalName: "grapes",
      amount: 1.0,
      unit: "small handful",
      meta: [],
      measures: {
        us: {
          amount: 1.0,
          unitShort: "small handful",
          unitLong: "small handful",
        },
        metric: {
          amount: 1.0,
          unitShort: "small handful",
          unitLong: "small handful",
        },
      },
    },
    {
      id: 9152,
      aisle: "Produce",
      image: "lemon-juice.jpg",
      consistency: "LIQUID",
      name: "juice of lemon",
      nameClean: "lemon juice",
      original: "juice of 1 lemon",
      originalName: "juice of lemon",
      amount: 1.0,
      unit: "",
      meta: [],
      measures: {
        us: { amount: 1.0, unitShort: "", unitLong: "" },
        metric: { amount: 1.0, unitShort: "", unitLong: "" },
      },
    },
    {
      id: 93611,
      aisle: "Milk, Eggs, Other Dairy",
      image: "buttermilk.jpg",
      consistency: "SOLID",
      name: "kefir",
      nameClean: "kefir",
      original: "1/2 cup plain kefir (can substitute buttermilk)",
      originalName: "plain kefir (can substitute buttermilk)",
      amount: 0.5,
      unit: "cup",
      meta: ["plain", "(can substitute buttermilk)"],
      measures: {
        us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
        metric: { amount: 118.294, unitShort: "ml", unitLong: "milliliters" },
      },
    },
    {
      id: 1001256,
      aisle: "Milk, Eggs, Other Dairy",
      image: "white-cream.png",
      consistency: "LIQUID",
      name: "plain greek yogurt",
      nameClean: "plain greek yogurt",
      original: "1/2 cup plain Greek yogurt",
      originalName: "plain Greek yogurt",
      amount: 0.5,
      unit: "cup",
      meta: ["plain"],
      measures: {
        us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
        metric: { amount: 118.294, unitShort: "ml", unitLong: "milliliters" },
      },
    },
    {
      id: 10011282,
      aisle: "Produce",
      image: "red-onion.png",
      consistency: "SOLID",
      name: "red onion",
      nameClean: "red onion",
      original: "1/4 cup chopped red onion",
      originalName: "chopped red onion",
      amount: 0.25,
      unit: "cup",
      meta: ["red", "chopped"],
      measures: {
        us: { amount: 0.25, unitShort: "cups", unitLong: "cups" },
        metric: { amount: 59.147, unitShort: "ml", unitLong: "milliliters" },
      },
    },
    {
      id: 1102047,
      aisle: "Spices and Seasonings",
      image: "salt-and-pepper.jpg",
      consistency: "SOLID",
      name: "salt and pepper",
      nameClean: "salt and pepper",
      original: "salt and pepper, to taste",
      originalName: "salt and pepper, to taste",
      amount: 3.0,
      unit: "servings",
      meta: ["to taste"],
      measures: {
        us: { amount: 3.0, unitShort: "servings", unitLong: "servings" },
        metric: { amount: 3.0, unitShort: "servings", unitLong: "servings" },
      },
    },
    {
      id: 11291,
      aisle: "Produce",
      image: "spring-onions.jpg",
      consistency: "SOLID",
      name: "scallions",
      nameClean: "spring onions",
      original: "4 scallions",
      originalName: "scallions",
      amount: 4.0,
      unit: "",
      meta: [],
      measures: {
        us: { amount: 4.0, unitShort: "", unitLong: "" },
        metric: { amount: 4.0, unitShort: "", unitLong: "" },
      },
    },
  ],
  id: 716437,
  title: "Chilled Cucumber Avocado Soup with Yogurt and Kefir",
  readyInMinutes: 45,
  servings: 3,
  sourceUrl:
    "http://fullbellysisters.blogspot.com/2012/06/chilled-cucumber-avocado-soup-with.html",
  image: "https://spoonacular.com/recipeImages/716437-556x370.jpg",
  imageType: "jpg",
  summary:
    'Chilled Cucumber Avocado Soup with Yogurt and Kefir might be just the soup you are searching for. One serving contains <b>183 calories</b>, <b>9g of protein</b>, and <b>7g of fat</b>. This gluten free, primal, and vegetarian recipe serves 3 and costs <b>$2.12 per serving</b>. 171 person have made this recipe and would make it again. It will be a hit at your <b>Autumn</b> event. Head to the store and pick up avocado, persian cucumbers, kefir, and a few other things to make it today. From preparation to the plate, this recipe takes about <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 97%</b>. This score is awesome. Try <a href="https://spoonacular.com/recipes/chilled-cucumber-avocado-and-yogurt-soup-21553">Chilled Cucumber, Avocado, and Yogurt Soup</a>, <a href="https://spoonacular.com/recipes/chilled-cucumber-yogurt-soup-499125">Chilled Cucumber-Yogurt Soup</a>, and <a href="https://spoonacular.com/recipes/chilled-cucumber-mint-yogurt-soup-608062">Chilled Cucumber Mint Yogurt Soup</a> for similar recipes.',
  cuisines: [],
  dishTypes: ["soup"],
  diets: ["gluten free", "lacto ovo vegetarian", "primal"],
  occasions: ["fall", "winter"],
  winePairing: {},
  instructions: "",
  analyzedInstructions: [],
  originalId: null,
  spoonacularSourceUrl:
    "https://spoonacular.com/chilled-cucumber-avocado-soup-with-yogurt-and-kefir-716437",
};
