// const soups = [
//   {
//     id: 716437,
//     title: "Chilled Cucumber Avocado Soup with Yogurt and Kefir",
//     image: "https://spoonacular.com/recipeImages/716437-312x231.jpg",
//     imageType: "jpg",
//   },
//   {
//     id: 663559,
//     title: "Tomato and lentil soup",
//     image: "https://spoonacular.com/recipeImages/663559-312x231.jpg",
//     imageType: "jpg",
//   },
//   {
//     id: 660405,
//     title: "Smoky Black Bean Soup With Sweet Potato & Kale",
//     image: "https://spoonacular.com/recipeImages/660405-312x231.jpg",
//     imageType: "jpg",
//   },
//   {
//     id: 636602,
//     title: "Butternut Squash Soup (In Half An Hour!)",
//     image: "https://spoonacular.com/recipeImages/636602-312x231.jpg",
//     imageType: "jpg",
//   },
//   {
//     id: 652393,
//     title: "Moosewood Lentil Soup",
//     image: "https://spoonacular.com/recipeImages/652393-312x231.jpg",
//     imageType: "jpg",
//   },
//   {
//     id: 633097,
//     title: "Autumn In A Bowl Soup",
//     image: "https://spoonacular.com/recipeImages/633097-312x231.jpg",
//     imageType: "jpg",
//   },
//   {
//     id: 652038,
//     title: "Minted Pea & Spinach Soup",
//     image: "https://spoonacular.com/recipeImages/652038-312x231.jpg",
//     imageType: "jpg",
//   },
//   {
//     id: 1096213,
//     title: "Creamy, Healthy Asparagus Soup with Avocado and Fennel",
//     image: "https://spoonacular.com/recipeImages/1096213-312x231.jpg",
//     imageType: "jpg",
//   },
//   {
//     id: 631834,
//     title: "10-Minute Bean Stew",
//     image: "https://spoonacular.com/recipeImages/631834-312x231.jpg",
//     imageType: "jpg",
//   },
//   {
//     id: 637164,
//     title: "Carrot and Coriander Soup",
//     image: "https://spoonacular.com/recipeImages/637164-312x231.jpg",
//     imageType: "jpg",
//   },
// ];

// const soup = {
//   vegetarian: true,
//   vegan: false,
//   glutenFree: true,
//   dairyFree: false,
//   veryHealthy: true,
//   cheap: false,
//   veryPopular: false,
//   sustainable: false,
//   lowFodmap: false,
//   weightWatcherSmartPoints: 3,
//   gaps: "no",
//   preparationMinutes: -1,
//   cookingMinutes: -1,
//   aggregateLikes: 171,
//   healthScore: 54,
//   creditsText: "Full Belly Sisters",
//   license: "CC BY-SA 3.0",
//   sourceName: "Full Belly Sisters",
//   pricePerServing: 216.29,
//   extendedIngredients: [
//     {
//       id: 9037,
//       aisle: "Produce",
//       image: "avocado.jpg",
//       consistency: "SOLID",
//       name: "avocado",
//       nameClean: "avocado",
//       original: "1/2 avocado",
//       originalName: "avocado",
//       amount: 0.5,
//       unit: "",
//       meta: [],
//       measures: {
//         us: { amount: 0.5, unitShort: "", unitLong: "" },
//         metric: { amount: 0.5, unitShort: "", unitLong: "" },
//       },
//     },
//     {
//       id: 11206,
//       aisle: "Produce",
//       image: "cucumber.jpg",
//       consistency: "SOLID",
//       name: "cucumbers",
//       nameClean: "cucumber",
//       original: "5-6 persian cucumbers",
//       originalName: "persian cucumbers",
//       amount: 5.0,
//       unit: "",
//       meta: [],
//       measures: {
//         us: { amount: 5.0, unitShort: "", unitLong: "" },
//         metric: { amount: 5.0, unitShort: "", unitLong: "" },
//       },
//     },
//     {
//       id: 9132,
//       aisle: "Produce",
//       image: "red-grapes.jpg",
//       consistency: "SOLID",
//       name: "grapes",
//       nameClean: "grapes",
//       original: "small handful of grapes",
//       originalName: "grapes",
//       amount: 1.0,
//       unit: "small handful",
//       meta: [],
//       measures: {
//         us: {
//           amount: 1.0,
//           unitShort: "small handful",
//           unitLong: "small handful",
//         },
//         metric: {
//           amount: 1.0,
//           unitShort: "small handful",
//           unitLong: "small handful",
//         },
//       },
//     },
//     {
//       id: 9152,
//       aisle: "Produce",
//       image: "lemon-juice.jpg",
//       consistency: "LIQUID",
//       name: "juice of lemon",
//       nameClean: "lemon juice",
//       original: "juice of 1 lemon",
//       originalName: "juice of lemon",
//       amount: 1.0,
//       unit: "",
//       meta: [],
//       measures: {
//         us: { amount: 1.0, unitShort: "", unitLong: "" },
//         metric: { amount: 1.0, unitShort: "", unitLong: "" },
//       },
//     },
//     {
//       id: 93611,
//       aisle: "Milk, Eggs, Other Dairy",
//       image: "buttermilk.jpg",
//       consistency: "SOLID",
//       name: "kefir",
//       nameClean: "kefir",
//       original: "1/2 cup plain kefir (can substitute buttermilk)",
//       originalName: "plain kefir (can substitute buttermilk)",
//       amount: 0.5,
//       unit: "cup",
//       meta: ["plain", "(can substitute buttermilk)"],
//       measures: {
//         us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
//         metric: { amount: 118.294, unitShort: "ml", unitLong: "milliliters" },
//       },
//     },
//     {
//       id: 1001256,
//       aisle: "Milk, Eggs, Other Dairy",
//       image: "white-cream.png",
//       consistency: "LIQUID",
//       name: "plain greek yogurt",
//       nameClean: "plain greek yogurt",
//       original: "1/2 cup plain Greek yogurt",
//       originalName: "plain Greek yogurt",
//       amount: 0.5,
//       unit: "cup",
//       meta: ["plain"],
//       measures: {
//         us: { amount: 0.5, unitShort: "cups", unitLong: "cups" },
//         metric: { amount: 118.294, unitShort: "ml", unitLong: "milliliters" },
//       },
//     },
//     {
//       id: 10011282,
//       aisle: "Produce",
//       image: "red-onion.png",
//       consistency: "SOLID",
//       name: "red onion",
//       nameClean: "red onion",
//       original: "1/4 cup chopped red onion",
//       originalName: "chopped red onion",
//       amount: 0.25,
//       unit: "cup",
//       meta: ["red", "chopped"],
//       measures: {
//         us: { amount: 0.25, unitShort: "cups", unitLong: "cups" },
//         metric: { amount: 59.147, unitShort: "ml", unitLong: "milliliters" },
//       },
//     },
//     {
//       id: 1102047,
//       aisle: "Spices and Seasonings",
//       image: "salt-and-pepper.jpg",
//       consistency: "SOLID",
//       name: "salt and pepper",
//       nameClean: "salt and pepper",
//       original: "salt and pepper, to taste",
//       originalName: "salt and pepper, to taste",
//       amount: 3.0,
//       unit: "servings",
//       meta: ["to taste"],
//       measures: {
//         us: { amount: 3.0, unitShort: "servings", unitLong: "servings" },
//         metric: { amount: 3.0, unitShort: "servings", unitLong: "servings" },
//       },
//     },
//     {
//       id: 11291,
//       aisle: "Produce",
//       image: "spring-onions.jpg",
//       consistency: "SOLID",
//       name: "scallions",
//       nameClean: "spring onions",
//       original: "4 scallions",
//       originalName: "scallions",
//       amount: 4.0,
//       unit: "",
//       meta: [],
//       measures: {
//         us: { amount: 4.0, unitShort: "", unitLong: "" },
//         metric: { amount: 4.0, unitShort: "", unitLong: "" },
//       },
//     },
//   ],
//   id: 716437,
//   title: "Chilled Cucumber Avocado Soup with Yogurt and Kefir",
//   readyInMinutes: 45,
//   servings: 3,
//   sourceUrl:
//     "http://fullbellysisters.blogspot.com/2012/06/chilled-cucumber-avocado-soup-with.html",
//   image: "https://spoonacular.com/recipeImages/716437-556x370.jpg",
//   imageType: "jpg",
//   summary:
//     'Chilled Cucumber Avocado Soup with Yogurt and Kefir might be just the soup you are searching for. One serving contains <b>183 calories</b>, <b>9g of protein</b>, and <b>7g of fat</b>. This gluten free, primal, and vegetarian recipe serves 3 and costs <b>$2.12 per serving</b>. 171 person have made this recipe and would make it again. It will be a hit at your <b>Autumn</b> event. Head to the store and pick up avocado, persian cucumbers, kefir, and a few other things to make it today. From preparation to the plate, this recipe takes about <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 97%</b>. This score is awesome. Try <a href="https://spoonacular.com/recipes/chilled-cucumber-avocado-and-yogurt-soup-21553">Chilled Cucumber, Avocado, and Yogurt Soup</a>, <a href="https://spoonacular.com/recipes/chilled-cucumber-yogurt-soup-499125">Chilled Cucumber-Yogurt Soup</a>, and <a href="https://spoonacular.com/recipes/chilled-cucumber-mint-yogurt-soup-608062">Chilled Cucumber Mint Yogurt Soup</a> for similar recipes.',
//   cuisines: [],
//   dishTypes: ["soup"],
//   diets: ["gluten free", "lacto ovo vegetarian", "primal"],
//   occasions: ["fall", "winter"],
//   winePairing: {},
//   instructions: "",
//   analyzedInstructions: [],
//   originalId: null,
//   spoonacularSourceUrl:
//     "https://spoonacular.com/chilled-cucumber-avocado-soup-with-yogurt-and-kefir-716437",
// };
